### ISSUE TITLE
请问下有数据库表设计吗

### ISSUE THREAD

**Issue by zhoutao1** [mikemelon/java-exam#3]
缺少sql文件

**Comment by mikemelon** [comment]
有了，刚加上。

**Comment by xzachen** [comment]
在吗？有个问题像请教一下  git clone你的文件之后跑不起来  一大堆的错误

**Comment by xzachen** [comment]
有人成功克隆然后利用mysql数据库跑起来了吗啊？

**Comment by mikemelon** [comment]
按说Hibernate会自动为MySQL建表的，数据库名是examdb。
不过需要的话也有很多运行的实际数据了，在src/main/resources/import下。
